version: "3"
# Define services/containers
services:
  # este lo creo yo
  php-apache:
    image: prueba
    environment:
      ## Perfecto esto me sobre escribe las de Dockerfile
      ## así a production va correctamente
      ENVIROMENT: development
    networks:
      - my-network
    ports:
      - "80:80"
    links:
      - "mysql"
    # volumes:
    #   - ${PWD}/src:/var/www/html

  # MySQL container
  mysql:
    # Use mysql:8.0.19 image
    image: mysql:latest
    # Connect to "my-network" network, as defined below
    networks:
      - my-network
    # Pass a list of environment variables to the container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: toor
    # Create presistence in mysql
    # volumes:
      # - ${PWD}/volume:/var/lib/mysql
      # - /home/docker/a-db/mysql/volume/:/var/lib/mysql

  # phpMyAdmin container
  phpmyadmin:
    # Use phpmyadmin/phpmyadmin:5.0.2 image
    image: phpmyadmin/phpmyadmin:latest
    # Connect to "my-network" network, as defined below
    networks:
      - my-network
    # Map port 8080 on the host to port 80 inside the container
    # Syntax is: "HOST_PORT:CONTAINER_PORT"
    ports:
      - "8080:80"
    # Pass a list of environment variables to the container
    environment:
      PMA_HOST: mysql
    # Wait for "mysql" container to start first 
    depends_on:
      - mysql

# Define networks
networks:
  my-network:
